name: Native-AMD64

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      #Setup Java
      - uses: actions/setup-java@v2
        with:
          distribution: 'liberica' # See 'Supported distributions' for available options
          java-version: '17'
      #Checkout Main
      - name: Checkout main
        uses: actions/checkout@v2
        with:
          submodules: true
      #Build Image
      - name: Build Image
        run: ./mvnw -Pnative-amd64 spring-boot:build-image -DskipTests -Dregistry.token=${{ secrets.GH_TOKEN }}
