name: Native-ARM64

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: arm64
    steps:
      #Checkout Main
      - name: Checkout main
        uses: actions/checkout@v2
        with:
          submodules: true
      #Build Image
      - name: Build Image
        run: ./mvnw -Pnative-arm64 spring-boot:build-image -DskipTests -Dregistry.token=${{ secrets.GH_TOKEN }} -Dregistry.user=${{ github.repository_owner }}
