name: Native-ARM64

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: arm64
    steps:
      #Checkout Main
      - name: Checkout main
        uses: actions/checkout@v2
        with:
          submodules: true
      #Registry Login
      - name: Log in to the container registry
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GH_TOKEN }}
      #Build Image
      - name: Build Image
        run: ./mvnw -Pnative-arm64 spring-boot:build-image -DskipTests
